### ISSUE TITLE
Erreur de la récuperation des noms des stations essences avec un accents

### ISSUE THREAD

**Issue by roumano** [vingerha/prixCarburant-home-assistant#1]
Salut,

Il semble y avoir un souci pour la recuperation du nom de la station d'essance quand celle-ci contient un accent (et/ou un retour chariot) : 
Avec cette configuration
```
- platform: prixCarburant
  stationID:
    - 38320006
```
Cela crée l'entité `PrixCarburant_38220003`
mais son `Station name` est vide 

Or sur le site https://www.prix-carburants.gouv.fr/, le nom de cette station est visible sous : `INTERMARCHE VIZILLE
Intermarché`  ( il semble aussi y avoir un retour chariot dans le nom)

**Comment by vingerha** [comment]
Car t'as donné deux ID, j'ai testé les deux et effectivement pour Intermarche (38220003) ça ne marche pas
38320006 : Relais d'EYBENS
38220003 : [vide] 
La raison : les détails des stations viennent d'un fichier, et pas du site-web...et le fichier n'est pas maintenu ni eu un maj depuis longtemps (années)
Car j'ai terminé cet fork en faveur du fork d'Aozhan, je vais voir avec lui si nous pouvons faire quelque chose mais j'avais déjà cherche des heures pour d'autres sources des stations sans résultats.
Noter bien que le fork d'Aozhan utilise le même fichier alors pas de solution pour l'instant

https://github.com/Aohzan/hass-prixcarburant/blob/master/README.fr.md

**Comment by vingerha** [comment]
Issue closed as no follow up will be given, please see link to fork of Aozhan where a possible solution may apply in the future (not now)
